CREATE TABLE transfers (
  id SERIAL PRIMARY KEY,
  transfer_id INT NOT NULL UNIQUE,
  account_id INT NOT NULL,
  date DATE NOT NULL,
  amount MONEY NOT NULL,
  balance MONEY NOT NULL,
  type VARCHAR(50) NOT NULL CHECK (type IN ('CREDIT', 'WITHDRAWAL')),
  operation VARCHAR(50) NOT NULL CHECK (operation IN ('CC_WITHDRAWAL', 'COLLECTION_FROM_OTHER_BANK', 'CREDIT_IN_CASH', 'REMITTANCE_TO_OTHER_BANK', 'WITHDRAWAL_IN_CASH', 'CC_CREDIT'))
);